# Generated by Django 3.2.6 on 2021-08-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
