# Generated by Django 3.2.6 on 2021-08-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
